Introduce weak references
RaRe-Technologies/sqlitedict pull request #165
Opened 2022-11-26 07:35 UTC by mpenkov

- Fix #69 
- Fix #48 (maybe)

Author is @Cologler

Continued from #153 because that branch was mistakenly deleted.

2022-11-26 07:37 UTC, mpenkov commented
@piskvorky @Cologler Please eyeball this PR and let me know if you spot anything odd

2022-11-26 07:41 UTC, Cologler commented
> @piskvorky @Cologler Please eyeball this PR and let me know if you spot anything odd

Looks Good To Me 👌.

2022-11-26 12:22 UTC, piskvorky requested changes

2022-11-26 12:22 UTC, piskvorky commented on sqlitedict.py
> +# _RESPONSES_NO_MORE command, which indicates nothing else will ever be written
```suggestion
# _RESPONSE_NO_MORE command, which indicates nothing else will ever be written
```

2022-11-26 12:38 UTC, Cologler commented
What if the user does some longtime work in the loop?

``` py
for value in a_sqlite_dict.values():
    # long timework here, like an HTTP request
    ...
```

2022-11-29 06:50 UTC, mpenkov commented
> What if the user does some longtime work in the loop?
> 
> ```python
> for value in a_sqlite_dict.values():
>     # longtime work here, like an HTTP request
>     ...
> ```

I think the response queue will continue to receive new items.

Basically, there is a [producer/consumer](https://en.wikipedia.org/wiki/Producer%E2%80%93consumer_problem) problem here. The producer is the sqlite thread and the consumer is the user. We want to produce results quickly enough for the user to consume them without overwhelming the user. If we produce too quickly (or the user is too slow to consume) then the queue grows in size and occupies more memory.

I think one way to solve that particular problem is to use fixed-size queues for the responses. If a queue is full, then it means the user is consuming faster than we are producing, and we can produce slower.

@piskvorky What do you think? Is there a reason why we use queues of unlimited size?

2022-12-01 13:08 UTC, piskvorky commented
> If a queue is full, then it means the user is consuming faster than we are producing, and we can produce slower.

Do you mean "consuming slower"?

Anyway, limiting the queue is technically easy, here:

https://github.com/RaRe-Technologies/sqlitedict/blob/8545a174a4a32bd2f8eb7c17d89899370138fe3a/sqlitedict.py#L623-L624

But I'm not sure about the implications. The code is sufficiently complex that blocking `put`s could lead to dead locks, unless we think through all the code paths very carefully. What happens when the consumers don't `get` (for whatever reason – generator, exception…), so that the `put` blocks forever?

2022-12-02 13:28 UTC, mpenkov commented
> Do you mean "consuming slower"?

Yes, sorry.

> Anyway, limiting the queue is technically easy, here:

Yes, as you point out, this is the easy part. The hard part is ensuring nothing else breaks.

> What happens when the consumers don't get (for whatever reason – generator, exception…), so that the put blocks forever?

Good question...

Anyway, I think this discussion is out of scope for this PR (but definitely helpful). I think we're done for now.

2022-12-03 04:42 UTC, merged